"""Generate Markdown and CSV reports from ASV benchmark results.

Reads the latest JSON results generated by ASV and formats them into
human-readable tables, saving them to the 'reports' directory.
"""

from __future__ import annotations

import json
import pathlib
import statistics
import sys
from collections import defaultdict
from typing import Any

from tabulate import tabulate

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS_DIR = PROJECT_ROOT / ".asv" / "results"
REPORTS_DIR = PROJECT_ROOT / "reports"

# Top-level files under .asv/results/ are metadata/indexes (benchmark
# definitions, machine info) rather than per-commit timing results, and must
# not be mistaken for a "latest results" file.
NON_RESULT_FILES = {"machine.json", "benchmarks.json"}


def _is_missing(value: Any) -> bool:
    """True if an ASV result value represents a missing/NaN/None entry."""
    if value is None:
        return True
    try:
        return isinstance(value, float) and value != value  # NaN check
    except TypeError:
        return False


def find_latest_results() -> dict[str, Any]:
    """Find the most recent ASV per-machine results JSON file."""
    if not RESULTS_DIR.exists():
        print(f"Error: Results directory not found at {RESULTS_DIR}", file=sys.stderr)
        print("Run 'asv run' first.", file=sys.stderr)
        sys.exit(1)

    # ASV stores actual per-commit results under .asv/results/MACHINE/COMMIT.json.
    # Files directly under RESULTS_DIR (benchmarks.json, machine.json) are
    # metadata/index files with no timing data and must be excluded, or the
    # "most recently modified" heuristic below picks the wrong file.
    result_files = [
        f
        for f in RESULTS_DIR.rglob("*.json")
        if f.name not in NON_RESULT_FILES and f.parent != RESULTS_DIR
    ]

    if not result_files:
        print("Error: No benchmark results found.", file=sys.stderr)
        sys.exit(1)

    latest_file = max(result_files, key=lambda p: p.stat().st_mtime)
    print(f"Reading results from: {latest_file.relative_to(PROJECT_ROOT)}")

    with open(latest_file) as f:
        return json.load(f)


def iter_benchmarks(raw: dict[str, Any]):
    """Yield (bench_name, entry) pairs, normalizing ASV's result schema.

    Modern ASV stores each benchmark's data as a flat list positioned
    according to top-level ``result_columns`` (columnar schema) rather than
    a per-benchmark dict; this reshapes either form into a dict so callers
    can use ``entry["result"]``, ``entry["stats_q_25"]``, etc. uniformly.
    """
    columns = raw.get("result_columns", [])
    for bench_name, row in raw.get("results", {}).items():
        if isinstance(row, dict):
            yield bench_name, row
        elif isinstance(row, list) and columns:
            yield bench_name, dict(zip(columns, row))


def format_time(seconds: float | None) -> str:
    """Format time in seconds to human readable string."""
    if _is_missing(seconds):
        return "N/A"

    if seconds < 0.001:
        return f"{seconds * 1_000_000:.1f} µs"
    elif seconds < 1.0:
        return f"{seconds * 1000:.1f} ms"
    else:
        return f"{seconds:.2f} s"


def format_memory(bytes_val: float | None) -> str:
    """Format memory in bytes to human readable string."""
    if _is_missing(bytes_val):
        return "N/A"

    mb = bytes_val / (1024 * 1024)
    if mb > 1024:
        return f"{mb / 1024:.2f} GB"
    return f"{mb:.1f} MB"


def format_value(value: float | None, bench_type: str) -> str:
    """Format value based on benchmark type."""
    if _is_missing(value):
        return "-"

    if bench_type.startswith("time_"):
        return format_time(value)
    elif bench_type.startswith("peakmem_"):
        return format_memory(value)
    elif bench_type.startswith("track_throughput") or bench_type.startswith(
        "track_pipeline_throughput"
    ):
        if value > 1_000_000:
            return f"{value / 1_000_000:.1f}M/s"
        elif value > 1_000:
            return f"{value / 1_000:.1f}K/s"
        return f"{value:.0f}/s"
    elif bench_type.startswith("track_speedup"):
        return f"{value:.1f}x"
    else:
        # Default numeric format
        if isinstance(value, float):
            return f"{value:.2f}"
        return str(value)


def variability_stats(entry: dict[str, Any], idx: int) -> dict[str, Any]:
    """Extract min/max/std/repeat-count for one param combo from an entry.

    Prefers raw per-repeat ``samples`` (only present when ASV is run with
    ``--record-samples``) for true min/max/std. Falls back to the
    always-available ``stats_q_25``/``stats_q_75`` quartiles as a coarser
    variability measure when raw samples were not recorded.
    """
    samples_col = entry.get("samples") or []
    samples = samples_col[idx] if idx < len(samples_col) else None
    repeat_col = entry.get("stats_repeat") or []
    number_col = entry.get("stats_number") or []
    repeat = repeat_col[idx] if idx < len(repeat_col) else None
    number = number_col[idx] if idx < len(number_col) else None

    if samples:
        return {
            "min": min(samples),
            "max": max(samples),
            "std": statistics.pstdev(samples) if len(samples) > 1 else 0.0,
            "median": statistics.median(samples),
            "n_samples": len(samples),
            "repeat": repeat,
            "number": number,
            "source": "samples",
        }

    q25_col = entry.get("stats_q_25") or []
    q75_col = entry.get("stats_q_75") or []
    q25 = q25_col[idx] if idx < len(q25_col) else None
    q75 = q75_col[idx] if idx < len(q75_col) else None
    if not _is_missing(q25) and not _is_missing(q75):
        return {
            "q25": q25,
            "q75": q75,
            "repeat": repeat,
            "number": number,
            "source": "quartiles",
        }

    return {"repeat": repeat, "number": number, "source": "none"}


def generate_reports() -> None:
    """Generate Markdown and CSV reports."""
    REPORTS_DIR.mkdir(exist_ok=True)
    results = find_latest_results()

    reports_md = ["# FreshData Benchmark Results\n\n"]

    # Group benchmarks by file (e.g. benchmark_missing)
    bench_groups: dict[str, dict[str, Any]] = defaultdict(dict)

    for bench_name, bench_data in iter_benchmarks(results):
        if "result" not in bench_data:
            continue

        parts = bench_name.split(".")
        if len(parts) < 3:
            continue

        group_name = parts[-2]  # e.g., BenchmarkMissing
        method_name = parts[-1]  # e.g., time_drop_missing

        bench_groups[group_name][method_name] = bench_data

    # Generate a table for each group
    for group_name, methods in sorted(bench_groups.items()):
        reports_md.append(f"## {group_name}\n")

        for method_name, data in sorted(methods.items()):
            reports_md.append(f"### `{method_name}`\n")

            param_names = data.get("params", [])
            # Skip non-parameterized or oddly parameterized methods for simple tables
            if not param_names or len(param_names) != 2:
                reports_md.append(
                    "_Requires 2 parameters (n_rows, library) for standard formatting._\n\n"
                )
                continue

            # Usually: params = [["10000", "100000"], ["freshdata", "pandas", ...]]
            row_sizes = param_names[0]
            libraries = param_names[1]

            result_list = data.get("result", [])

            # ASV flattens the cartesian product of params with the FIRST
            # param (n_rows) varying slowest and the LAST param (library)
            # varying fastest: idx = size_idx * len(libraries) + lib_idx.
            # The table is library-per-row/size-per-column, so cells must be
            # gathered in that (size-outer, library-inner) order and then
            # transposed into per-library rows.
            headers = ["Library"] + [f"{size} rows" for size in row_sizes]
            cells_by_lib: dict[str, list[str]] = {lib: [] for lib in libraries}

            idx = 0
            for _size in row_sizes:
                for lib in libraries:
                    val = result_list[idx] if idx < len(result_list) else None
                    cell = format_value(val, method_name)
                    stats = variability_stats(data, idx)
                    if stats["source"] == "samples":
                        cell += f" (σ={format_time(stats['std'])}, n={stats['n_samples']})"
                    elif stats["source"] == "quartiles" and method_name.startswith(
                        ("time_", "peakmem_")
                    ):
                        fmt = format_time if method_name.startswith("time_") else format_memory
                        cell += f" (IQR {fmt(stats['q25'])}-{fmt(stats['q75'])})"
                    cells_by_lib[lib].append(cell)
                    idx += 1

            table_data = [[lib] + cells_by_lib[lib] for lib in libraries]

            md_table = tabulate(table_data, headers=headers, tablefmt="github")
            reports_md.append(md_table + "\n\n")

    # Write Markdown report
    md_path = REPORTS_DIR / "summary.md"
    with open(md_path, "w") as f:
        f.write("".join(reports_md))

    print(f"Generated Markdown report: {md_path}")

    # Save raw structured data, including variability stats per param combo
    extracted: dict[str, dict[str, Any]] = {}
    for group_name, methods in bench_groups.items():
        extracted[group_name] = {}
        for method_name, data in methods.items():
            param_names = data.get("params", [])
            result_list = data.get("result", [])
            entries = []
            for idx, val in enumerate(result_list):
                stats = variability_stats(data, idx)
                entries.append({"index": idx, "result": val, **stats})
            extracted[group_name][method_name] = {
                # "params"/"result" preserved verbatim (original ASV flat
                # order: first param slowest-varying, last param
                # fastest-varying) for consumers like generate_plots.py.
                "params": param_names,
                "result": result_list,
                "stats": entries,
            }

    json_path = REPORTS_DIR / "results_extracted.json"
    with open(json_path, "w") as f:
        json.dump(extracted, f, indent=2)

    print(f"Generated JSON extract: {json_path}")


if __name__ == "__main__":
    generate_reports()
